apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
    volume.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: construct
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix
  name: matrix-construct-data
  namespace: matrix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cinder-csi-ssd
  volumeMode: Filesystem
