---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-csi-s3
  namespace: flux-system
spec:
  chart:
    spec:
      chart: csi-s3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-csi-s3
  interval: 1h0m0s
  releaseName: k8s-csi-s3
  targetNamespace: flux-system
  values:
    secret:
      create: false # Already created with a sealed secret
      name: k8s-csi-s3-secret

    images:
      # Test for fixing unmount spam
      csi: ghcr.io/morguldir/k8s-csi-s3:merge-152 

